name: default
prometheus:
  render: mimirtool
grafana:
  render: grizzly
mixins:
  base:
    config:
      mimirNamespace: base
      grafanaDashboardFolder: Base
      serverLinuxLink: '/d/dashboardlink'
      baseClusterLink: '/d/dashboardlink'
    source:
      directory:
        path: /mixins/base-mixin
  node:
    config:
      mimirNamespace: node
      grafanaDashboardFolder: Platform
    source:
      git:
        url: https://github.com/prometheus/node_exporter.git
        ref: master
        depth: 1
      includePaths:
        - docs/node-mixin/**/*
      newRootPath: docs/node-mixin
  windows:
    config:
      mimirNamespace: windows
      grafanaDashboardFolder: Base
    source:
      git:
        url: https://github.com/grafana/jsonnet-libs.git
        ref: master
        depth: 1
      includePaths:
        - windows-mixin/**/*
      newRootPath: windows-mixin
libs:
  windows-observ-lib:
    source:
      git:
        url: https://github.com/grafana/jsonnet-libs.git
        ref: master
        depth: 1
      includePaths:
        - windows-observ-lib/**/*
      newRootPath: windows-observ-lib
