name: example-observ-lib
prometheus:
  render: mimirtool
grafana:
  render: grizzly
mixins:
  windows:
    config:
      mimirNamespace: windows
      grafanaDashboardFolder: Base
    source:
      git:
        url: https://github.com/grafana/jsonnet-libs.git
        ref: master
        depth: 1
      includePaths:
        - windows-mixin/**/*
      newRootPath: windows-mixin
libs:
  windows-observ-lib:
    source:
      git:
        url: https://github.com/grafana/jsonnet-libs.git
        ref: master
        depth: 1
      includePaths:
        - windows-observ-lib/**/*
      newRootPath: windows-observ-lib
