site_name: Monitor Tools
site_description: A collection of tools and scripts for managing monitoring resources as code.

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Usage:
    - Scripts: scripts.md
    - Configuration: configuration.md
  - Reference:
    - Software: software.md

markdown_extensions:
  - toc:
      permalink: true
